version: '3.1'
services:
  backend:
    depends_on:
      - redis-container
    build: ./backend
    image: ${docker_username}/backend:latest
    environment:
      REDIS_DNS: redis-container
    restart: always
  
  frontend:
    depends_on:
      - backend
    build: ./frontend
    image: ${docker_username}/frontend:latest
    ports:
      - 8080:8080
    environment:
      BACKEND_DNS: backend
    
  redis-container:
    image: "redis:latest"
    restart: always
    volumes: 
      - redis_data:/data

volumes:
  redis_data: