kind: Service
apiVersion: v1
metadata:
  labels:
    app: deployment-frontend
  name:  service-frontend
spec:
  selector:
    app:  deployment-frontend
  type:  NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080