kind: Service
apiVersion: v1
metadata:
  name:  service-backend
  labels:
    app: deployment-backend
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app:  deployment-backend
  type:  ClusterIP
  