name: main-flow
on:
  pull_request:
    branches:
      - main
jobs:
  clone-down:
    runs-on: staging
    steps:
      - name: clone-down
        uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: | 
            .
            !.git
  build:
    runs-on: staging
    needs: [Clone-down]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v3
        with: 
          name: code
          path: .
      - name: build-frontend
        run: cd frontend && go build .    
      - name: build-backend
        run: cd backend &&  go mod download github.com/gomodule/redigo && go build . 
  test:
    runs-on: staging
    needs: [build]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v3
        with: 
          name: code
          path: .
      - name: test-front-end
        run: cd frontend && go test .  
  publish:
    runs-on: staging
    needs: [test]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v3
        with: 
          name: code
          path: .
      - name: test-front-end
        run: docker-compose up --build -d  