name: publish-flow
on:
  push:
    branches:
      - 03_container_registry    
#      - main
jobs:
  clone-down:
    runs-on: production
    steps:
      - name: clone-down
        uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: | 
            .
            !.git
  publish:
    runs-on: production
    needs: [clone-down]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v3
        with: 
          name: code
          path: .
      - name: test-front-end
        run: docker-compose up --build -d
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $docker_username/micronaut-app:1.0-${GIT_COMMIT::8}    
    