name: publish-flow
on:
  push:
    branches:
      - 03_container_registry    
#      - main
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  clone-down:
    runs-on: production
    steps:
      - name: clone-down
        uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: | 
            .
            !.git
  publish:
    runs-on: production
    needs: [clone-down]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v3
        with: 
          name: code
          path: .
      - name: test-front-end
        run: docker-compose up --build -d
  push-docker-image:
    runs-on: ubuntu-latest
    needs: [clone-down]
    steps:
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend 
          push: true
          tags: armandasrokas/simple-fortune-cookie-app
          #tags: $docker_username/simple-fortune-cookie-app:1.0-${GIT_COMMIT::8} 
    